---
ID: "2b9d3dc2-4c6e-417a-bf95-9b3eab368a11"
Parent: "bdeff2e6-e141-429a-a62b-2a6ebe52b5e2"
Template: "c14bf746-030f-4e59-8594-395f6d299e61"
Path: "/sitecore/content/demo/nextjs-app/Settings/Shared Sites Settings"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230519T134148Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f68965dc-9a08-4c45-8430-c2d6cd81c464"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230519T134148Z
